import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Post from '../components/post/post'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My Posts
        </h1>

        <ul className={styles.posts}>
          <li>
            <Post 
            content="hello testing here.." 
            date="26/12/2021">
            </Post>
          </li>
          <li>
            <Post 
            content="This is a chitter challenge and the need to put lots of text here to see the container." 
            date="26/12/2021">
            </Post>            
          </li>
          <li>
            <Post 
            content="This is a chitter challenge!"
            date="20/12/2021">
            </Post>
          </li>
          <li>
            <Post 
            content="This is a chitter challenge!"
            date="20/12/2021">            
            </Post>
          </li>
        </ul>

        <form>
          <textarea className={styles.formContent}></textarea>
            <button className={styles.formButton}>
              Add New Post
            </button>          
        </form>

      </main>

      
    </div>
  )
}
